import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { PlusCircle, Users, BookOpen, Presentation } from 'lucide-react'
import Link from 'next/link'

export function TeacherDashboard({ profile }: { profile: any }) {
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Welcome, {profile.full_name}</h2>
          <p className="text-muted-foreground">Manage your classrooms, assignments, and AI quizzes.</p>
        </div>
        <div className="flex gap-2">
          <Button className="bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white shadow-md">
            <PlusCircle className="mr-2 h-4 w-4" />
            New Class
          </Button>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card className="bg-white/50 dark:bg-black/40 backdrop-blur-md border-white/20">
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-sm font-medium">Total Students</CardTitle>
            <Users className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">0</div>
            <p className="text-xs text-muted-foreground">Across all active classes</p>
          </CardContent>
        </Card>
        <Card className="bg-white/50 dark:bg-black/40 backdrop-blur-md border-white/20">
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-sm font-medium">Active Assignments</CardTitle>
            <BookOpen className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">0</div>
            <p className="text-xs text-muted-foreground">Needs grading: 0</p>
          </CardContent>
        </Card>
        <Card className="bg-white/50 dark:bg-black/40 backdrop-blur-md border-white/20">
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-sm font-medium">Quizzes Created</CardTitle>
            <Presentation className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">0</div>
            <p className="text-xs text-muted-foreground">Generated by AI: 0</p>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-7 mt-6">
        <Card className="col-span-4 bg-white/50 dark:bg-black/40 backdrop-blur-md border-white/20">
          <CardHeader>
            <CardTitle>Recent Activity</CardTitle>
            <CardDescription>Your students' recent submissions and quiz scores.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex h-[300px] items-center justify-center rounded-md border border-dashed border-slate-300 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-900/50">
              <p className="text-sm text-muted-foreground">No recent activity yet. Create a class to get started!</p>
            </div>
          </CardContent>
        </Card>

        <Card className="col-span-3 bg-white/50 dark:bg-black/40 backdrop-blur-md border-white/20">
          <CardHeader>
            <CardTitle>Quick Actions</CardTitle>
            <CardDescription>Common tools for your workflow.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <Link href="/dashboard/quiz/new" className="block w-full">
              <Button variant="outline" className="w-full justify-start h-14 border-indigo-200 dark:border-indigo-900 hover:bg-indigo-50 dark:hover:bg-indigo-950/50">
                <Presentation className="mr-3 h-5 w-5 text-indigo-500" />
                <div className="text-left">
                  <div className="font-semibold text-sm">Generate Quiz with AI</div>
                  <div className="text-xs text-muted-foreground">Upload a PDF to create a Kahoot-style quiz.</div>
                </div>
              </Button>
            </Link>
            
            <Link href="/dashboard/assignments/new" className="block w-full">
              <Button variant="outline" className="w-full justify-start h-14 border-pink-200 dark:border-pink-900 hover:bg-pink-50 dark:hover:bg-pink-950/50">
                <BookOpen className="mr-3 h-5 w-5 text-pink-500" />
                <div className="text-left">
                  <div className="font-semibold text-sm">Create Assignment</div>
                  <div className="text-xs text-muted-foreground">Draft a new homework assignment.</div>
                </div>
              </Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
